### ISSUE TITLE
Pitsby does not load correctly after following install steps: "Failed to instantiate module pitsby-app..."

### ISSUE THREAD

**Issue by jfsaliba** [glorious-codes/glorious-pitsby-demo#14]
I'm trying to get this repo to build as part of getting started with Pitsby, but I am unable to get Pitsby to run in the browser.

I've followed all the steps in the readme, and even installed node fresh on a separate computer and followed the steps again. The build and start commands seem to succeed, but loading up the application in the browser results in a blank screen and 2 console errors:

![image](https://user-images.githubusercontent.com/395902/193698448-f108471d-99c7-4ed8-8e20-d2a8c6fcc3ad.png)

`main.js:2269 Uncaught Error: Module parse failed: Unexpected token (1:0)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders`

and

`angular.js:138 Uncaught Error: [$injector:modulerr] Failed to instantiate module pitsby-app due to:
Error: [$injector:nomod] Module 'pitsby-app' is not available! You either misspelled the module name or forgot to load it. If registering a module ensure that you specify the dependencies as the second argument.`

My current environment looks like this:

- node 16.17.1
- npm 8.15.0

Any suggestions on where to look to get this repo running?

**Comment by rafaelcamargo** [comment]
Hey, @jfsaliba!

Sorry for the late reply. Just run the project here and everything went fine. That is, I couldn't reproduce your issue.

In addition, I also updated some dependencies (@glorious/pitsby [1.31.0 → 1.33.0] and react [16.12.0 → 17.0.2]) and just re-deployed the demo into production.

Reading the error printed in your screenshot, it seems that the dependency `html-loader` didn't behave accordingly. So, please, try the following:
a) `git pull (master branch)`
b) `rm -rf ./node_modules`
c) `npm i`
d) `rm -rf ./dist`
e) `npm run build`
f) `npm run docs`

Let me know if this works for you.

**Comment by m-cisse-easy-live** [comment]
> Hey, @jfsaliba!
> 
> Sorry for the late reply. Just run the project here and everything went fine. That is, I couldn't reproduce your issue.
> 
> In addition, I also updated some dependencies (@glorious/pitsby [1.31.0 → 1.33.0] and react [16.12.0 → 17.0.2]) and just re-deployed the demo into production.
> 
> Reading the error printed in your screenshot, it seems that the dependency `html-loader` didn't behave accordingly. So, please, try the following: a) `git pull (master branch)` b) `rm -rf ./node_modules` c) `npm i` d) `rm -rf ./dist` e) `npm run build` f) `npm run docs`
> 
> Let me know if this works for you.

Hello,

I've installed this demo and I'm having the same problem. 
![image](https://github.com/user-attachments/assets/5ef3269d-efef-4b9b-84cc-aa9d7acef47a)

I applied the order suite you recommended: 
> b) rm -rf ./node_modules
c) npm i
d) rm -rf ./dist
e) npm run build
f) npm run docs

My environment : 
- node 18.17.1
- npm 9.6.7
- Windows 10
